# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
  - task: NodeTool@0
    displayName: install nodejs
    inputs:
      versionSpec: '16.x'
  - task: CmdLine@2
    inputs:
      script: |
        cd src/socket.io
        npm install
        npm run install
        nohup npm start &
        cd ../../
  - task: UseDotNet@2
    displayName: install .NET SDK
    inputs:
      packageType: 'sdk'
      version: '6.x'
  - task: DotNetCoreCLI@2
    displayName: dotnet test SocketIOClient.UnitTest.csproj
    inputs:
      command: 'test'
      projects: 'src/SocketIOClient.UnitTest.csproj'
  - task: DotNetCoreCLI@2
    displayName: dotnet test SocketIOClient.IntegrationTests.csproj
    inputs:
      command: 'test'
      projects: 'src/SocketIOClient.IntegrationTests.csproj'
