name: Publish ${{ parameters.package }}
trigger: none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: package
    displayName: Package
    type: string
    values:
      - SocketIO.Core
      - SocketIO.Serializer.Core
      - SocketIOClient
      - SocketIOClient.Windows7
      - SocketIO.Serializer.MessagePack
      - SocketIO.Serializer.NewtonsoftJson
      - SocketIO.Serializer.SystemTextJson

jobs:
  - job:
    displayName: Publish ${{ parameters.package }}
    steps:
      - pwsh: |
          dotnet pack -c Release --output $(Build.ArtifactStagingDirectory)
          $packageName = Get-ChildItem $(Build.ArtifactStagingDirectory)/${{ parameters.package }}.*.nupkg | Select-Object -First 1 -ExpandProperty Name
          Write-Host "##vso[task.setvariable variable=packageName;]$packageName"
        displayName: dotnet pack
        workingDirectory: $(Agent.BuildDirectory)/s/src/${{ parameters.package }}
      - task: NuGetAuthenticate@1
        inputs:
          nuGetServiceConnections: NuGet
      - task: NuGetCommand@2
        displayName: Publish ${{ parameters.package }}
        workingDirectory: $(Build.ArtifactStagingDirectory)
        inputs:
          command: push
          nuGetFeedType: external
          publishFeedCredentials: nuget.org
