name: Publish
trigger: none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: package
    displayName: Package
    type: string
    values:
      - SocketIOClient
      - SocketIOClient.Windows7
      - SocketIOClient.Newtonsoft.Json

jobs:
  - job:
    displayName: Publish
    steps:
      - task: PowerShell@2
        displayName: dotnet pack
        inputs:
          workingDirectory: $(Agent.BuildDirectory)/s/src/${{ parameters.package }}
          script: |
            dotnet pack -c Release --output $(Build.ArtifactStagingDirectory)
            $packageName = Get-ChildItem ${{ parameters.package }}.*.nupkg | Select-Object -First 1 -ExpandProperty Name
            Write-Host "##vso[task.setvariable variable=packageName;]$packageName"
            # dotnet nuget push $packageName --api-key AzureArtifacts --source nuget.org
      - task: CmdLine@2
        displayName: Publish to nuget.org
        inputs:
          workingDirectory: $(Agent.ArtifactStagingDirectory)
          script: |
            echo $(packageName)
