name: Release
trigger: none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: SocketIOClient
    displayName: SocketIOClient
    type: boolean
    default: false

jobs:
  - job:
    displayName: Pack and Push
    steps:
      - ${{ if parameters.SocketIOClient }}:
        - task: DotNetCoreCLI@2
          displayName: Pack SocketIOClient
          inputs:
            workingDirectory: $(Build.ArtifactStagingDirectory)/s/src/SocketIOClient
            command: pack
            outputDir: $(Build.ArtifactStagingDirectory)
        - task: CmdLine@2
          inputs:
            script: |
              ls $(Build.ArtifactStagingDirectory)
        - task: DotNetCoreCLI@2
          displayName: Push SocketIOClient to nuget.org
          inputs:
            workingDirectory: $(Build.ArtifactStagingDirectory)/s/src/SocketIOClient
            command: push
            nuGetFeedType: external
            externalEndpoint: NuGetApiKey
