name: Release
trigger: none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: SocketIOClient
    displayName: SocketIOClient
    type: boolean
    default: false

jobs:
  - job:
    displayName: Pack and Push
    steps:
      - template: templates/net-sdk.yml
      - task: CmdLine@2
        inputs:
          script: |
            dotnet --version
      - task:
        - ${{ if parameters.SocketIOClient }}:
          - task: DotNetCoreCLI@2
            displayName: Pack SocketIOClient
            inputs:
              workingDirectory: $(Agent.BuildDirectory)/s/src/SocketIOClient
              command: pack
              # project: SocketIOClient.csproj
              outputDir: $(Build.ArtifactStagingDirectory)
          - task: DotNetCoreCLI@2
            displayName: Push SocketIOClient to nuget.org
            inputs:
              workingDirectory: $(Build.ArtifactStagingDirectory)/s/src/SocketIOClient
              command: push
              nuGetFeedType: external
              externalEndpoint: NuGetApiKey
