name: Release
trigger: none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: SocketIOClient
    displayName: SocketIOClient
    type: boolean
    default: false

jobs:
  - job:
    displayName: Pack and Push
    steps:
      - template: templates/net-sdk.yml
      - ${{ if parameters.SocketIOClient }}:
        - task: DotNetCoreCLI@2
          displayName: Pack to Artifact
          inputs:
            workingDirectory: $(Agent.BuildDirectory)/s/src/SocketIOClient
            command: pack
            outputDir: $(Build.ArtifactStagingDirectory)
        - task: DotNetCoreCLI@2
          displayName: Push to nuget.org
          inputs:
            workingDirectory: $(Build.ArtifactStagingDirectory)/s/src/SocketIOClient
            command: push
            nuGetFeedType: external
            externalEndpoint: NuGetApiKey
