name: Release
trigger: none

pool:
  vmImage: ubuntu-latest

# parameters:
#   - name: configuration
#     displayName: Configuration
#     type: string
#     default: Release
#     values:
#       - Release
#   - name: version_suffix
#     displayName: Version Suffix
#     type: string
#   - name: package_version
#     displayName: Package Version
#     type: string

jobs:
  - job:
    displayName: Pack and Push
    steps:
      - template: templates/net-sdk.yml
      - task: DotNetCoreCLI@2
        displayName: Pack to Artifact
        inputs:
          workingDirectory: $(Agent.BuildDirectory)/s/src/SocketIOClient
          command: pack
          outputDir: $(Build.ArtifactStagingDirectory)
      - task: DotNetCoreCLI@2
        displayName: Push to nuget.org
        inputs:
          workingDirectory: $(Build.ArtifactStagingDirectory)/s/src/SocketIOClient
          command: push
          nuGetFeedType: external
          externalEndpoint: NuGetApiKey
