name: Run unit tests and integration tests

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
  - task: NodeTool@0
    displayName: Install nodejs
    inputs:
      versionSpec: '16.x'

  - task: CmdLine@2
    displayName: Run socket.io server
    inputs:
      script: |
        workingDirectory: src/socket.io
        npm install
        npm run install
        nohup npm start

  - task: UseDotNet@2
    displayName: Install .NET 6 SDK
    inputs:
      packageType: 'sdk'
      version: '6.x'

  - task: DotNetCoreCLI@2
    displayName: Run unit tests
    inputs:
      workingDirectory: $(Agent.BuildDirectory)
      command: 'test'
      projects: 'src/SocketIOClient.UnitTest/SocketIOClient.UnitTest.csproj'

  - task: DotNetCoreCLI@2
    displayName: Run integration tests
    inputs:
      command: 'test'
      projects: 'src/SocketIOClient.IntegrationTests/SocketIOClient.IntegrationTests.csproj'
